package com.hy.racing.entity;

// default package
// Generated 2017-5-3 17:20:02 by Hibernate Tools 4.3.5.Final

/**
 * Cargroup generated by hbm2java
 */
public class Cargroup implements java.io.Serializable {

	private Integer id;
	private String name;
	private String description;//描述
	private Integer status;

	public Cargroup() {
	}

	public Cargroup(String name, Integer status) {
		this.name = name;
		this.status = status;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

}
