package com.hy.racing.entity;
// default package
// Generated 2017-5-3 17:20:02 by Hibernate Tools 4.3.5.Final

/**
 * Carinfo generated by hbm2java
 */
public class Carinfo implements java.io.Serializable {

	private Integer id;
	private Integer cartypeId;
	private Integer cargroupId;
	private Integer userId;
	private Integer status;

	public Carinfo() {
	}

	public Carinfo(Integer cartypeId, Integer cargroupId, Integer userId, Integer status) {
		this.cartypeId = cartypeId;
		this.cargroupId = cargroupId;
		this.userId = userId;
		this.status = status;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getCartypeId() {
		return this.cartypeId;
	}

	public void setCartypeId(Integer cartypeId) {
		this.cartypeId = cartypeId;
	}

	public Integer getCargroupId() {
		return this.cargroupId;
	}

	public void setCargroupId(Integer cargroupId) {
		this.cargroupId = cargroupId;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

}
