package com.hy.racing.entity;
// default package
// Generated 2017-5-3 17:20:02 by Hibernate Tools 4.3.5.Final

/**
 * CommonSysParam generated by hbm2java
 */
public class CommonSysParam implements java.io.Serializable {

	private Integer paramid;
	private String paramname;
	private String paramval;
	private String paramdesc;
	private Integer status;
	private Integer catalogid;

	public CommonSysParam() {
	}

	public CommonSysParam(String paramname, String paramval) {
		this.paramname = paramname;
		this.paramval = paramval;
	}

	public CommonSysParam(String paramname, String paramval, String paramdesc, Integer status, Integer catalogid) {
		this.paramname = paramname;
		this.paramval = paramval;
		this.paramdesc = paramdesc;
		this.status = status;
		this.catalogid = catalogid;
	}

	public Integer getParamid() {
		return this.paramid;
	}

	public void setParamid(Integer paramid) {
		this.paramid = paramid;
	}

	public String getParamname() {
		return this.paramname;
	}

	public void setParamname(String paramname) {
		this.paramname = paramname;
	}

	public String getParamval() {
		return this.paramval;
	}

	public void setParamval(String paramval) {
		this.paramval = paramval;
	}

	public String getParamdesc() {
		return this.paramdesc;
	}

	public void setParamdesc(String paramdesc) {
		this.paramdesc = paramdesc;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Integer getCatalogid() {
		return this.catalogid;
	}

	public void setCatalogid(Integer catalogid) {
		this.catalogid = catalogid;
	}

}
