package com.hy.racing.entity;
// default package
// Generated 2017-5-3 17:20:02 by Hibernate Tools 4.3.5.Final

/**
 * CommonDictInfo generated by hbm2java
 */
public class CommonDictInfo implements java.io.Serializable {

	private Integer dictid;
	private String tablename;
	private String fieldname;
	private String fieldval;
	private String parentfieldval;
	private String fielddesc;
	private Integer selected;
	private Integer sort;
	private Integer state;

	public CommonDictInfo() {
	}

	public CommonDictInfo(String tablename, String fieldname, String fieldval, String parentfieldval, String fielddesc,
			Integer selected, Integer sort, Integer state) {
		this.tablename = tablename;
		this.fieldname = fieldname;
		this.fieldval = fieldval;
		this.parentfieldval = parentfieldval;
		this.fielddesc = fielddesc;
		this.selected = selected;
		this.sort = sort;
		this.state = state;
	}

	public Integer getDictid() {
		return this.dictid;
	}

	public void setDictid(Integer dictid) {
		this.dictid = dictid;
	}

	public String getTablename() {
		return this.tablename;
	}

	public void setTablename(String tablename) {
		this.tablename = tablename;
	}

	public String getFieldname() {
		return this.fieldname;
	}

	public void setFieldname(String fieldname) {
		this.fieldname = fieldname;
	}

	public String getFieldval() {
		return this.fieldval;
	}

	public void setFieldval(String fieldval) {
		this.fieldval = fieldval;
	}

	public String getParentfieldval() {
		return this.parentfieldval;
	}

	public void setParentfieldval(String parentfieldval) {
		this.parentfieldval = parentfieldval;
	}

	public String getFielddesc() {
		return this.fielddesc;
	}

	public void setFielddesc(String fielddesc) {
		this.fielddesc = fielddesc;
	}

	public Integer getSelected() {
		return this.selected;
	}

	public void setSelected(Integer selected) {
		this.selected = selected;
	}

	public Integer getSort() {
		return this.sort;
	}

	public void setSort(Integer sort) {
		this.sort = sort;
	}

	public Integer getState() {
		return this.state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

}
