package com.hy.racing.entity;
// default package
// Generated 2017-5-3 17:20:02 by Hibernate Tools 4.3.5.Final

import java.util.Date;

/**
 * Gameinfo generated by hbm2java
 */
public class Gameinfo implements java.io.Serializable {

	private Integer id;
	private Integer roundId;
	private Integer carId;
	private String speed;
	private String logtime;
	private Integer status;

	public Gameinfo() {
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getRoundId() {
		return this.roundId;
	}

	public void setRoundId(Integer roundId) {
		this.roundId = roundId;
	}

	public Integer getCarId() {
		return this.carId;
	}

	public void setCarId(Integer carId) {
		this.carId = carId;
	}

	public String getSpeed() {
		return this.speed;
	}

	public void setSpeed(String speed) {
		this.speed = speed;
	}

	public String getLogtime() {
		return this.logtime;
	}

	public void setLogtime(String logtime) {
		this.logtime = logtime;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

}
