package com.hy.racing.entity;
// Generated 2017-5-18 17:49:40 by Hibernate Tools 4.0.1.Final

import java.util.Date;

/**
 * Orderinfo generated by hbm2java
 */
public class Orderinfo implements java.io.Serializable {

	private Integer id;
	private Integer userId;
	private Integer orderType;// 订单类型，报名费，海选，复赛，决赛等
	private String orderNo;
	private Float totalPrice;
	private Date orderTime;
	private String payType;// 支付类型，微信，支付宝等
	private Integer status;// 暂时没用

	public Orderinfo() {
	}

	public Orderinfo(Integer userId, Integer orderType, String orderNo, Float totalPrice, Date orderTime,
			String payType, Integer status) {
		this.userId = userId;
		this.orderType = orderType;
		this.orderNo = orderNo;
		this.totalPrice = totalPrice;
		this.orderTime = orderTime;
		this.payType = payType;
		this.status = status;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public Integer getOrderType() {
		return this.orderType;
	}

	public void setOrderType(Integer orderType) {
		this.orderType = orderType;
	}

	public String getOrderNo() {
		return this.orderNo;
	}

	public void setOrderNo(String orderNo) {
		this.orderNo = orderNo;
	}

	public Float getTotalPrice() {
		return this.totalPrice;
	}

	public void setTotalPrice(Float totalPrice) {
		this.totalPrice = totalPrice;
	}

	public Date getOrderTime() {
		return this.orderTime;
	}

	public void setOrderTime(Date orderTime) {
		this.orderTime = orderTime;
	}

	public String getPayType() {
		return this.payType;
	}

	public void setPayType(String payType) {
		this.payType = payType;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

}
