package com.hy.racing.entity;
// Generated 2017-5-18 17:48:44 by Hibernate Tools 4.0.1.Final

import java.util.Date;

/**
 * Roundinfo generated by hbm2java
 */
public class Roundinfo implements java.io.Serializable {

	private Integer id;
	private String name;
	private Integer pid;
	private Date begintime;
	private Integer status;

	public Roundinfo() {
	}

	public Roundinfo(String name, Integer pid, Date begintime, Integer status) {
		this.name = name;
		this.pid = pid;
		this.begintime = begintime;
		this.status = status;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getPid() {
		return this.pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	public Date getBegintime() {
		return this.begintime;
	}

	public void setBegintime(Date begintime) {
		this.begintime = begintime;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

}
