package com.hy.racing.entity;
// default package

// Generated 2017-5-3 17:20:02 by Hibernate Tools 4.3.5.Final

import java.util.Date;

/**
 * Userinfo generated by hbm2java
 */
public class Userinfo implements java.io.Serializable {

	private Integer id;
	private String tel;
	private String username;
	private String sex;
	private String openid;
	private Date regtime;
	private Integer carteamId;
	private Integer status;

	public Userinfo() {
	}

	public Userinfo(String tel, String username, String sex, String openid, Date regtime, Integer carteamId,
			Integer status) {
		this.tel = tel;
		this.username = username;
		this.sex = sex;
		this.openid = openid;
		this.regtime = regtime;
		this.carteamId = carteamId;
		this.status = status;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getOpenid() {
		return this.openid;
	}

	public void setOpenid(String openid) {
		this.openid = openid;
	}

	public Date getRegtime() {
		return this.regtime;
	}

	public void setRegtime(Date regtime) {
		this.regtime = regtime;
	}

	public Integer getCarteamId() {
		return this.carteamId;
	}

	public void setCarteamId(Integer carteamId) {
		this.carteamId = carteamId;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

}
